name: Find unverified Github Actions
description: Scans your Github Actions Workflows for unverified actions
outputs:
  found-verified-actions:
    description: Whether ot not unverified actions are found to be used
  unverified-actions:
    description: JSON array of unverified actions found to be used
runs:
  using: 'node12'
  main: 'dist/index.js'
